In [168]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [169]:
data = pd.read_csv("kc_house_data.csv")

# Data Preprocessing

In [171]:
data=data.drop(["id","date","yr_renovated","zipcode"],axis=1)
data["sqft_living15"]=data["sqft_living"]-data["sqft_living15"]
data["sqft_lot15"]=data["sqft_lot"]-data["sqft_lot15"]

In [172]:
data

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,lat,long,sqft_living15,sqft_lot15
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,47.5112,-122.257,-160,0
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,47.7210,-122.319,880,-397
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,47.7379,-122.233,-1950,1938
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,47.5208,-122.393,600,0
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,47.6168,-122.045,-120,577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,47.6993,-122.346,0,-378
21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,47.5107,-122.362,480,-1387
21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,47.5944,-122.299,0,-657
21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,47.5345,-122.069,190,1101
21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,47.5941,-122.299,0,-281

In [173]:
y=data.iloc[:,0].values
x=data.iloc[:,1:].values

In [174]:
data.corr()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,lat,long,sqft_living15,sqft_lot15
price,1.000000,0.308350,0.525138,0.702035,0.089661,0.256794,0.266369,0.397293,0.036362,0.667434,0.605567,0.323816,0.054012,0.307003,0.021626,0.405392,0.050591
bedrooms,0.308350,1.000000,0.515884,0.576671,0.031703,0.175429,-0.006582,0.079532,0.028472,0.356967,0.477600,0.303093,0.154178,-0.008931,0.129473,0.434767,0.017802
bathrooms,0.525138,0.515884,1.000000,0.754665,0.087740,0.500653,0.063744,0.187737,-0.124982,0.664983,0.685342,0.283770,0.506019,0.024573,0.223042,0.504948,0.043373
sqft_living,0.702035,0.576671,0.754665,1.000000,0.172826,0.353949,0.103818,0.284611,-0.058753,0.762704,0.876597,0.435043,0.318049,0.052529,0.240223,0.665761,0.074506
sqft_lot,0.089661,0.031703,0.087740,0.172826,1.000000,-0.005201,0.021604,0.074710,-0.008958,0.113621,0.183512,0.015286,0.053080,-0.085683,0.229521,0.099227,0.754059
floors,0.256794,0.175429,0.500653,0.353949,-0.005201,1.000000,0.023698,0.029444,-0.263768,0.458183,0.523885,-0.245705,0.489319,0.049614,0.125419,0.221784,0.003191
waterfront,0.266369,-0.006582,0.063744,0.103818,0.021604,0.023698,1.000000,0.401857,0.016653,0.082775,0.072075,0.080588,-0.026161,-0.014274,-0.041910,0.060068,0.001955
view,0.397293,0.079532,0.187737,0.284611,0.074710,0.029444,0.401857,1.000000,0.045990,0.251321,0.167649,0.276947,-0.053440,0.006157,-0.078400,0.115158,0.038495
condition,0.036362,0.028472,-0.124982,-0.058753,-0.008958,-0.263768,0.016653,0.045990,1.000000,-0.144674,-0.158214,0.174105,-0.361417,-0.014941,-0.106500,0.016079,-0.009618
grade,0.667434,0.356967,0.664983,0.762704,0.113621,0.458183,0.082775,0.251321,-0.144674,1.000000,0.755923,0.168392,0.446963,0.114084,0.198372,0.352317,0.050163
sqft_above,0.605567,0.477600,0.685342,0.876597,0.183512,0.523885,0.072075,0.167649,-0.158214,0.755923,1.000000,-0.051943,0.423898,-0.000816,0.343803,0.505124,0.079650
sqft_basement,0.323816,0.303093,0.283770,0.435043,0.015286,-0.245705,0.080588,0.276947,0.174105,0.168392,-0.051943,1.000000,-0.133124,0.110538,-0.144765,0.436476,0.005584
yr_built,0.054012,0.154178,0.506019,0.318049,0.053080,0.489319,-0.026161,-0.053440,-0.361417,0.446963,0.423898,-0.133124,1.000000,-0.148122,0.409356,0.114037,0.009033
lat,0.307003,-0.008931,0.024573,0.052529,-0.085683,0.049614,-0.014274,0.006157,-0.014941,0.114084,-0.000816,0.110538,-0.148122,1.000000,-0.135512,0.024564,-0.041141
long,0.021626,0.129473,0.223042,0.240223,0.229521,0.125419,-0.041910,-0.078400,-0.106500,0.198372,0.343803,-0.144765,0.409356,-0.135512,1.000000,-0.014488,0.088522
sqft_living15,0.405392,0.434767,0.504948,0.665761,0.099227,0.221784,0.060068,0.115158,0.016079,0.352317,0.505124,0.436476,0.114037,0.024564,-0.014488,1.000000,0.074916
sqft_lot15,0.050591,0.017802,0.043373,0.074506,0.754059,0.003191,0.001955,0.038495,-0.009618,0.050163,0.079650,0.005584,0.009033,-0.041141,0.088522,0.074916,1.000000

In [175]:
from scipy.stats import pearsonr
correlations = []
p_values = []
# Calculate Pearson correlation and p-value for each feature
for feature in x.T:
    corr, p_value = pearsonr(feature, y)
    correlations.append(corr)
    p_values.append(p_value)

In [176]:
correlations

[0.30834959814562846,
 0.5251375054139688,
 0.7020350546118027,
 0.08966086058710017,
 0.25679388755070814,
 0.2663694340305992,
 0.39729348829453925,
 0.03636178912900033,
 0.6674342560201706,
 0.605567298356079,
 0.32381602071198745,
 0.054011531494792965,
 0.3070034799952186,
 0.021626241039306802,
 0.4053916635356436,
 0.050590661476336764]

In [177]:
p_values

[0.0,
 0.0,
 0.0,
 7.972504510431418e-40,
 1.6e-322,
 0.0,
 0.0,
 8.9356540624392e-08,
 0.0,
 0.0,
 0.0,
 1.929872809402505e-15,
 0.0,
 0.0014750922063359916,
 0.0,
 9.928445587470263e-14]

## Dataset Split

In [179]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

# Training

## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score,accuracy_score
from sklearn.model_selection import cross_val_score
model5 = RandomForestRegressor(n_estimators=100)
model5.fit(x_train,y_train)
accuracies = cross_val_score(estimator = model5,X = x_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))
print("Accuracy on test set: "+str(round(model5.score(x_test,y_test)*100,3))+"%")